insert into public.cafes (
  name,
  slug,
  city,
  neighborhood,
  address,
  description,
  long_description,
  price_range,
  rating,
  review_count,
  vibes,
  amenities,
  image_url,
  maps_url,
  instagram_url,
  featured,
  wifi_friendly,
  source,
  status
)
values
  (
    'Seperempat Lab',
    'seperempat-lab-jakarta',
    'Jakarta',
    'Kebayoran Baru',
    'Jl. Wijaya I No.63, Jakarta Selatan',
    'Coffee bar terang dengan espresso clean, meja kerja nyaman, dan crowd produktif.',
    'Seperempat Lab cocok untuk sesi fokus di siang hari lalu lanjut santai sore. Ada banyak colokan, kursi ergonomis, dan menu kopi susu sampai manual brew yang konsisten.',
    '$$',
    4.8,
    412,
    array['Work-friendly','Minimal','Specialty coffee'],
    array['WiFi cepat','Colokan banyak','Indoor AC','Parking','Brunch'],
    'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
    'https://maps.google.com/?q=Seperempat+Lab+Jakarta',
    'https://instagram.com/seperempatcoffee',
    true,
    true,
    'editorial',
    'published'
  ),
  (
    'Titik Temu Bali',
    'titik-temu-bali-seminyak',
    'Bali',
    'Seminyak',
    'Jl. Kayu Aya No.40, Seminyak',
    'Hidden gem tropis untuk brunch, meeting santai, dan nongkrong setelah pantai.',
    'Titik Temu punya outdoor yang adem, pastry solid, dan ambience yang cocok untuk catch-up atau kerja ringan. Crowd internasional bikin tempat ini terasa hidup sepanjang hari.',
    '$$$',
    4.7,
    356,
    array['Tropical','Brunch','Social'],
    array['WiFi cepat','Outdoor','Parking','Brunch','Pet friendly'],
    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
    'https://maps.google.com/?q=Titik+Temu+Bali+Seminyak',
    'https://instagram.com/titiktemucoffee',
    true,
    true,
    'editorial',
    'published'
  )
on conflict (slug) do nothing;
